stages:
  - discover-submodules
  - build


#################### DISCOVER-SUBMODULES STAGE ####################

discover-submodules:
  stage: discover-submodules
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./ci/find-submodules.sh -n
  artifacts:
    paths:
      - all-submodules.csv
  tags:
    - shell-docker-light
  dependencies: []


#################### BUILD STAGE ####################

.docker_wait_img_template: &docker_wait_img_template
  stage: build
  variables:
    GIT_STRATEGY: none
    NUM: "60"
    SLEEP: "10"
    RETAG: "1"
  script:
    - SHA=$(grep ^$REPO, all-submodules.csv | cut -d, -f2)
    - IMGTAG="$IMG:$TAG_PREFIX$SHA$TAG_SUFFIX"
    - echo "Will pull docker image $IMGTAG"
    - for i in $(seq 1 $NUM); do docker pull $IMGTAG && OK=1 && break || sleep $SLEEP; done
    - if [ -z "$OK" ]; then echo "ERROR Couldn't pull $IMGTAG!" && exit 1; fi
    - if [ -z "$RETAG" ]; then exit 0; fi
    - IMGTAG2="$IMG:io-$TAG_PREFIX$CI_COMMIT_SHA$TAG_SUFFIX"
    - echo "Retagging using mist.io sha"
    - echo "$IMGTAG -> $IMGTAG2"
    - docker tag $IMGTAG $IMGTAG2
    - docker push $IMGTAG2
    - IMGTAG2="$IMG:io-$TAG_PREFIX$CI_COMMIT_REF_SLUG$TAG_SUFFIX"
    - echo "Retagging using mist.io branch"
    - echo "$IMGTAG -> $IMGTAG2"
    - docker tag $IMGTAG $IMGTAG2
    - docker push $IMGTAG2
  tags:
    - shell-docker-light
  dependencies:
    - discover-submodules

wait-api-image:
  <<: *docker_wait_img_template
  before_script:
    - REPO=mistio/mist.api
    - IMG=gcr.io/mist-ops/mist
    - TAG_PREFIX=api-

wait-ui-image:
  <<: *docker_wait_img_template
  before_script:
    - REPO=mistio/mist.ui
    - IMG=gcr.io/mist-ops/ui

wait-landing-image:
  <<: *docker_wait_img_template
  before_script:
    - REPO=mistio/mist.landing
    - IMG=gcr.io/mist-ops/landing

alpine_base_manual_build:
  stage: build
  when: manual
  script:
    - cd docker/alpine
    - docker build --rm -t gcr.io/mist-ops/alpine:3.4 .
    - docker tag gcr.io/mist-ops/alpine:3.4 mist/alpine:3.4
    - docker push gcr.io/mist-ops/alpine:3.4
    - docker push mist/alpine:3.4
  tags:
    - builder
  dependencies: []
